eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: true

spring:
  application:
    name: PRODUCT-CONSUMER
  rabbitmq:
    host: 192.168.1.223
    port: 5672
    username: guest
    password: guest

#随机访问
PRODUCT-PROVIDER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

server:
  port: 80
