spring:
  application:
    name: PRODUCT-CONSUMER
  rabbitmq:
    host: 192.168.1.223
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      discovery:
        enable: true
        service-id: config
      profile: dev
server:
  port: 80
